import localFont from "next/font/local";
import "../Styles/css/main.css";

import { Major_Mono_Display } from 'next/font/google'

const major = Major_Mono_Display({ subsets: ['latin'], weight: '400', variable: "--font-major" })

import { Montserrat } from 'next/font/google'
 
const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-montserrat' })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${major.variable}`}>
        {children}
      </body>
    </html>
  );
}
